//Test code generated by MISTA

package test;

import src.*;
import junit.framework.*;

public class MainTester_RTD extends TestCase{

	private Main main;
	
	protected void setUp()  throws Exception {
		main = new Main();
		main.onList.add("Testes");
		main.onList.add("Verificação");
		main.onList.add("Validação");
		main.onList.add("Software");
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		try {
			main.addString("Testes");
			System.out.println("Test failed at test 1_1: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_1", main.onList.contains("Testes"));
		assertTrue("1_1", main.onList.contains("Verificação"));
		assertTrue("1_1", main.onList.contains("Validação"));
		assertTrue("1_1", main.onList.contains("Software"));
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		main.removeString("Testes");
		assertTrue("1_2", main.onList.contains("Verificação"));
		assertTrue("1_2", main.onList.contains("Validação"));
		assertTrue("1_2", main.onList.contains("Software"));
		assertTrue("1_2", main.offList.contains("Testes"));
		main.addString("Testes");
		assertTrue("1_2_1", main.onList.contains("Testes"));
		assertTrue("1_2_1", main.onList.contains("Verificação"));
		assertTrue("1_2_1", main.onList.contains("Validação"));
		assertTrue("1_2_1", main.onList.contains("Software"));
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		main.removeString("Testes");
		main.removeString("Verificação");
		assertTrue("1_2_2", main.onList.contains("Validação"));
		assertTrue("1_2_2", main.onList.contains("Software"));
		assertTrue("1_2_2", main.offList.contains("Testes"));
		assertTrue("1_2_2", main.offList.contains("Verificação"));
		main.addString("Testes");
		assertTrue("1_2_2_1", main.onList.contains("Testes"));
		assertTrue("1_2_2_1", main.onList.contains("Validação"));
		assertTrue("1_2_2_1", main.onList.contains("Software"));
		assertTrue("1_2_2_1", main.offList.contains("Verificação"));
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.addString("Verificação");
		assertTrue("1_2_2_2", main.onList.contains("Verificação"));
		assertTrue("1_2_2_2", main.onList.contains("Validação"));
		assertTrue("1_2_2_2", main.onList.contains("Software"));
		assertTrue("1_2_2_2", main.offList.contains("Testes"));
	}

	public void test5() throws Exception {
		System.out.println("Test case 5");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		assertTrue("1_2_2_3", main.onList.contains("Software"));
		assertTrue("1_2_2_3", main.offList.contains("Testes"));
		assertTrue("1_2_2_3", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3", main.offList.contains("Validação"));
		main.addString("Testes");
		assertTrue("1_2_2_3_1", main.onList.contains("Testes"));
		assertTrue("1_2_2_3_1", main.onList.contains("Software"));
		assertTrue("1_2_2_3_1", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3_1", main.offList.contains("Validação"));
	}

	public void test6() throws Exception {
		System.out.println("Test case 6");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.addString("Verificação");
		assertTrue("1_2_2_3_2", main.onList.contains("Verificação"));
		assertTrue("1_2_2_3_2", main.onList.contains("Software"));
		assertTrue("1_2_2_3_2", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_2", main.offList.contains("Validação"));
	}

	public void test7() throws Exception {
		System.out.println("Test case 7");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.addString("Validação");
		assertTrue("1_2_2_3_3", main.onList.contains("Validação"));
		assertTrue("1_2_2_3_3", main.onList.contains("Software"));
		assertTrue("1_2_2_3_3", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_3", main.offList.contains("Verificação"));
	}

	public void test8() throws Exception {
		System.out.println("Test case 8");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		assertTrue("1_2_2_3_4", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_4", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3_4", main.offList.contains("Validação"));
		assertTrue("1_2_2_3_4", main.offList.contains("Software"));
		main.addString("Testes");
		assertTrue("1_2_2_3_4_1", main.onList.contains("Testes"));
		assertTrue("1_2_2_3_4_1", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3_4_1", main.offList.contains("Validação"));
		assertTrue("1_2_2_3_4_1", main.offList.contains("Software"));
	}

	public void test9() throws Exception {
		System.out.println("Test case 9");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Verificação");
		assertTrue("1_2_2_3_4_2", main.onList.contains("Verificação"));
		assertTrue("1_2_2_3_4_2", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_4_2", main.offList.contains("Validação"));
		assertTrue("1_2_2_3_4_2", main.offList.contains("Software"));
	}

	public void test10() throws Exception {
		System.out.println("Test case 10");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Validação");
		assertTrue("1_2_2_3_4_3", main.onList.contains("Validação"));
		assertTrue("1_2_2_3_4_3", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_4_3", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3_4_3", main.offList.contains("Software"));
	}

	public void test11() throws Exception {
		System.out.println("Test case 11");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_2_2_3_4_4", main.onList.contains("Software"));
		assertTrue("1_2_2_3_4_4", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_4_4", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3_4_4", main.offList.contains("Validação"));
	}

	public void test12() throws Exception {
		System.out.println("Test case 12");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		try {
			main.removeString("Testes");
			System.out.println("Test failed at test 1_2_2_3_4_5: an expected exception is not thrown!");
			System.exit(1);
		} catch (Exception e) {}
		assertTrue("1_2_2_3_4_5", main.offList.contains("Testes"));
		assertTrue("1_2_2_3_4_5", main.offList.contains("Verificação"));
		assertTrue("1_2_2_3_4_5", main.offList.contains("Validação"));
		assertTrue("1_2_2_3_4_5", main.offList.contains("Software"));
	}

	public void test13() throws Exception {
		System.out.println("Test case 13");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		assertTrue("1_2_2_4", main.onList.contains("Validação"));
		assertTrue("1_2_2_4", main.offList.contains("Testes"));
		assertTrue("1_2_2_4", main.offList.contains("Verificação"));
		assertTrue("1_2_2_4", main.offList.contains("Software"));
		main.addString("Testes");
		assertTrue("1_2_2_4_1", main.onList.contains("Testes"));
		assertTrue("1_2_2_4_1", main.onList.contains("Validação"));
		assertTrue("1_2_2_4_1", main.offList.contains("Verificação"));
		assertTrue("1_2_2_4_1", main.offList.contains("Software"));
	}

	public void test14() throws Exception {
		System.out.println("Test case 14");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		main.addString("Verificação");
		assertTrue("1_2_2_4_2", main.onList.contains("Verificação"));
		assertTrue("1_2_2_4_2", main.onList.contains("Validação"));
		assertTrue("1_2_2_4_2", main.offList.contains("Testes"));
		assertTrue("1_2_2_4_2", main.offList.contains("Software"));
	}

	public void test15() throws Exception {
		System.out.println("Test case 15");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_2_2_4_3", main.onList.contains("Validação"));
		assertTrue("1_2_2_4_3", main.onList.contains("Software"));
		assertTrue("1_2_2_4_3", main.offList.contains("Testes"));
		assertTrue("1_2_2_4_3", main.offList.contains("Verificação"));
	}

	public void test16() throws Exception {
		System.out.println("Test case 16");
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		main.removeString("Validação");
		assertTrue("1_2_2_4_4", main.offList.contains("Testes"));
		assertTrue("1_2_2_4_4", main.offList.contains("Verificação"));
		assertTrue("1_2_2_4_4", main.offList.contains("Validação"));
		assertTrue("1_2_2_4_4", main.offList.contains("Software"));
	}

	public void test17() throws Exception {
		System.out.println("Test case 17");
		main.removeString("Testes");
		main.removeString("Validação");
		assertTrue("1_2_3", main.onList.contains("Verificação"));
		assertTrue("1_2_3", main.onList.contains("Software"));
		assertTrue("1_2_3", main.offList.contains("Testes"));
		assertTrue("1_2_3", main.offList.contains("Validação"));
		main.addString("Testes");
		assertTrue("1_2_3_1", main.onList.contains("Testes"));
		assertTrue("1_2_3_1", main.onList.contains("Verificação"));
		assertTrue("1_2_3_1", main.onList.contains("Software"));
		assertTrue("1_2_3_1", main.offList.contains("Validação"));
	}

	public void test18() throws Exception {
		System.out.println("Test case 18");
		main.removeString("Testes");
		main.removeString("Validação");
		main.addString("Validação");
		assertTrue("1_2_3_2", main.onList.contains("Verificação"));
		assertTrue("1_2_3_2", main.onList.contains("Validação"));
		assertTrue("1_2_3_2", main.onList.contains("Software"));
		assertTrue("1_2_3_2", main.offList.contains("Testes"));
	}

	public void test19() throws Exception {
		System.out.println("Test case 19");
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Verificação");
		assertTrue("1_2_3_3", main.onList.contains("Software"));
		assertTrue("1_2_3_3", main.offList.contains("Testes"));
		assertTrue("1_2_3_3", main.offList.contains("Verificação"));
		assertTrue("1_2_3_3", main.offList.contains("Validação"));
	}

	public void test20() throws Exception {
		System.out.println("Test case 20");
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		assertTrue("1_2_3_4", main.onList.contains("Verificação"));
		assertTrue("1_2_3_4", main.offList.contains("Testes"));
		assertTrue("1_2_3_4", main.offList.contains("Validação"));
		assertTrue("1_2_3_4", main.offList.contains("Software"));
		main.addString("Testes");
		assertTrue("1_2_3_4_1", main.onList.contains("Testes"));
		assertTrue("1_2_3_4_1", main.onList.contains("Verificação"));
		assertTrue("1_2_3_4_1", main.offList.contains("Validação"));
		assertTrue("1_2_3_4_1", main.offList.contains("Software"));
	}

	public void test21() throws Exception {
		System.out.println("Test case 21");
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Validação");
		assertTrue("1_2_3_4_2", main.onList.contains("Verificação"));
		assertTrue("1_2_3_4_2", main.onList.contains("Validação"));
		assertTrue("1_2_3_4_2", main.offList.contains("Testes"));
		assertTrue("1_2_3_4_2", main.offList.contains("Software"));
	}

	public void test22() throws Exception {
		System.out.println("Test case 22");
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_2_3_4_3", main.onList.contains("Verificação"));
		assertTrue("1_2_3_4_3", main.onList.contains("Software"));
		assertTrue("1_2_3_4_3", main.offList.contains("Testes"));
		assertTrue("1_2_3_4_3", main.offList.contains("Validação"));
	}

	public void test23() throws Exception {
		System.out.println("Test case 23");
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Verificação");
		assertTrue("1_2_3_4_4", main.offList.contains("Testes"));
		assertTrue("1_2_3_4_4", main.offList.contains("Verificação"));
		assertTrue("1_2_3_4_4", main.offList.contains("Validação"));
		assertTrue("1_2_3_4_4", main.offList.contains("Software"));
	}

	public void test24() throws Exception {
		System.out.println("Test case 24");
		main.removeString("Testes");
		main.removeString("Software");
		assertTrue("1_2_4", main.onList.contains("Verificação"));
		assertTrue("1_2_4", main.onList.contains("Validação"));
		assertTrue("1_2_4", main.offList.contains("Testes"));
		assertTrue("1_2_4", main.offList.contains("Software"));
		main.addString("Testes");
		assertTrue("1_2_4_1", main.onList.contains("Testes"));
		assertTrue("1_2_4_1", main.onList.contains("Verificação"));
		assertTrue("1_2_4_1", main.onList.contains("Validação"));
		assertTrue("1_2_4_1", main.offList.contains("Software"));
	}

	public void test25() throws Exception {
		System.out.println("Test case 25");
		main.removeString("Testes");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_2_4_2", main.onList.contains("Verificação"));
		assertTrue("1_2_4_2", main.onList.contains("Validação"));
		assertTrue("1_2_4_2", main.onList.contains("Software"));
		assertTrue("1_2_4_2", main.offList.contains("Testes"));
	}

	public void test26() throws Exception {
		System.out.println("Test case 26");
		main.removeString("Testes");
		main.removeString("Software");
		main.removeString("Verificação");
		assertTrue("1_2_4_3", main.onList.contains("Validação"));
		assertTrue("1_2_4_3", main.offList.contains("Testes"));
		assertTrue("1_2_4_3", main.offList.contains("Verificação"));
		assertTrue("1_2_4_3", main.offList.contains("Software"));
	}

	public void test27() throws Exception {
		System.out.println("Test case 27");
		main.removeString("Testes");
		main.removeString("Software");
		main.removeString("Validação");
		assertTrue("1_2_4_4", main.onList.contains("Verificação"));
		assertTrue("1_2_4_4", main.offList.contains("Testes"));
		assertTrue("1_2_4_4", main.offList.contains("Validação"));
		assertTrue("1_2_4_4", main.offList.contains("Software"));
	}

	public void test28() throws Exception {
		System.out.println("Test case 28");
		main.removeString("Verificação");
		assertTrue("1_3", main.onList.contains("Testes"));
		assertTrue("1_3", main.onList.contains("Validação"));
		assertTrue("1_3", main.onList.contains("Software"));
		assertTrue("1_3", main.offList.contains("Verificação"));
		main.addString("Verificação");
		assertTrue("1_3_1", main.onList.contains("Testes"));
		assertTrue("1_3_1", main.onList.contains("Verificação"));
		assertTrue("1_3_1", main.onList.contains("Validação"));
		assertTrue("1_3_1", main.onList.contains("Software"));
	}

	public void test29() throws Exception {
		System.out.println("Test case 29");
		main.removeString("Verificação");
		main.removeString("Testes");
		assertTrue("1_3_2", main.onList.contains("Validação"));
		assertTrue("1_3_2", main.onList.contains("Software"));
		assertTrue("1_3_2", main.offList.contains("Testes"));
		assertTrue("1_3_2", main.offList.contains("Verificação"));
	}

	public void test30() throws Exception {
		System.out.println("Test case 30");
		main.removeString("Verificação");
		main.removeString("Validação");
		assertTrue("1_3_3", main.onList.contains("Testes"));
		assertTrue("1_3_3", main.onList.contains("Software"));
		assertTrue("1_3_3", main.offList.contains("Verificação"));
		assertTrue("1_3_3", main.offList.contains("Validação"));
		main.addString("Verificação");
		assertTrue("1_3_3_1", main.onList.contains("Testes"));
		assertTrue("1_3_3_1", main.onList.contains("Verificação"));
		assertTrue("1_3_3_1", main.onList.contains("Software"));
		assertTrue("1_3_3_1", main.offList.contains("Validação"));
	}

	public void test31() throws Exception {
		System.out.println("Test case 31");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.addString("Validação");
		assertTrue("1_3_3_2", main.onList.contains("Testes"));
		assertTrue("1_3_3_2", main.onList.contains("Validação"));
		assertTrue("1_3_3_2", main.onList.contains("Software"));
		assertTrue("1_3_3_2", main.offList.contains("Verificação"));
	}

	public void test32() throws Exception {
		System.out.println("Test case 32");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Testes");
		assertTrue("1_3_3_3", main.onList.contains("Software"));
		assertTrue("1_3_3_3", main.offList.contains("Testes"));
		assertTrue("1_3_3_3", main.offList.contains("Verificação"));
		assertTrue("1_3_3_3", main.offList.contains("Validação"));
	}

	public void test33() throws Exception {
		System.out.println("Test case 33");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		assertTrue("1_3_3_4", main.onList.contains("Testes"));
		assertTrue("1_3_3_4", main.offList.contains("Verificação"));
		assertTrue("1_3_3_4", main.offList.contains("Validação"));
		assertTrue("1_3_3_4", main.offList.contains("Software"));
		main.addString("Verificação");
		assertTrue("1_3_3_4_1", main.onList.contains("Testes"));
		assertTrue("1_3_3_4_1", main.onList.contains("Verificação"));
		assertTrue("1_3_3_4_1", main.offList.contains("Validação"));
		assertTrue("1_3_3_4_1", main.offList.contains("Software"));
	}

	public void test34() throws Exception {
		System.out.println("Test case 34");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Validação");
		assertTrue("1_3_3_4_2", main.onList.contains("Testes"));
		assertTrue("1_3_3_4_2", main.onList.contains("Validação"));
		assertTrue("1_3_3_4_2", main.offList.contains("Verificação"));
		assertTrue("1_3_3_4_2", main.offList.contains("Software"));
	}

	public void test35() throws Exception {
		System.out.println("Test case 35");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_3_3_4_3", main.onList.contains("Testes"));
		assertTrue("1_3_3_4_3", main.onList.contains("Software"));
		assertTrue("1_3_3_4_3", main.offList.contains("Verificação"));
		assertTrue("1_3_3_4_3", main.offList.contains("Validação"));
	}

	public void test36() throws Exception {
		System.out.println("Test case 36");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Testes");
		assertTrue("1_3_3_4_4", main.offList.contains("Testes"));
		assertTrue("1_3_3_4_4", main.offList.contains("Verificação"));
		assertTrue("1_3_3_4_4", main.offList.contains("Validação"));
		assertTrue("1_3_3_4_4", main.offList.contains("Software"));
	}

	public void test37() throws Exception {
		System.out.println("Test case 37");
		main.removeString("Verificação");
		main.removeString("Software");
		assertTrue("1_3_4", main.onList.contains("Testes"));
		assertTrue("1_3_4", main.onList.contains("Validação"));
		assertTrue("1_3_4", main.offList.contains("Verificação"));
		assertTrue("1_3_4", main.offList.contains("Software"));
		main.addString("Verificação");
		assertTrue("1_3_4_1", main.onList.contains("Testes"));
		assertTrue("1_3_4_1", main.onList.contains("Verificação"));
		assertTrue("1_3_4_1", main.onList.contains("Validação"));
		assertTrue("1_3_4_1", main.offList.contains("Software"));
	}

	public void test38() throws Exception {
		System.out.println("Test case 38");
		main.removeString("Verificação");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_3_4_2", main.onList.contains("Testes"));
		assertTrue("1_3_4_2", main.onList.contains("Validação"));
		assertTrue("1_3_4_2", main.onList.contains("Software"));
		assertTrue("1_3_4_2", main.offList.contains("Verificação"));
	}

	public void test39() throws Exception {
		System.out.println("Test case 39");
		main.removeString("Verificação");
		main.removeString("Software");
		main.removeString("Testes");
		assertTrue("1_3_4_3", main.onList.contains("Validação"));
		assertTrue("1_3_4_3", main.offList.contains("Testes"));
		assertTrue("1_3_4_3", main.offList.contains("Verificação"));
		assertTrue("1_3_4_3", main.offList.contains("Software"));
	}

	public void test40() throws Exception {
		System.out.println("Test case 40");
		main.removeString("Verificação");
		main.removeString("Software");
		main.removeString("Validação");
		assertTrue("1_3_4_4", main.onList.contains("Testes"));
		assertTrue("1_3_4_4", main.offList.contains("Verificação"));
		assertTrue("1_3_4_4", main.offList.contains("Validação"));
		assertTrue("1_3_4_4", main.offList.contains("Software"));
	}

	public void test41() throws Exception {
		System.out.println("Test case 41");
		main.removeString("Validação");
		assertTrue("1_4", main.onList.contains("Testes"));
		assertTrue("1_4", main.onList.contains("Verificação"));
		assertTrue("1_4", main.onList.contains("Software"));
		assertTrue("1_4", main.offList.contains("Validação"));
		main.addString("Validação");
		assertTrue("1_4_1", main.onList.contains("Testes"));
		assertTrue("1_4_1", main.onList.contains("Verificação"));
		assertTrue("1_4_1", main.onList.contains("Validação"));
		assertTrue("1_4_1", main.onList.contains("Software"));
	}

	public void test42() throws Exception {
		System.out.println("Test case 42");
		main.removeString("Validação");
		main.removeString("Testes");
		assertTrue("1_4_2", main.onList.contains("Verificação"));
		assertTrue("1_4_2", main.onList.contains("Software"));
		assertTrue("1_4_2", main.offList.contains("Testes"));
		assertTrue("1_4_2", main.offList.contains("Validação"));
	}

	public void test43() throws Exception {
		System.out.println("Test case 43");
		main.removeString("Validação");
		main.removeString("Verificação");
		assertTrue("1_4_3", main.onList.contains("Testes"));
		assertTrue("1_4_3", main.onList.contains("Software"));
		assertTrue("1_4_3", main.offList.contains("Verificação"));
		assertTrue("1_4_3", main.offList.contains("Validação"));
	}

	public void test44() throws Exception {
		System.out.println("Test case 44");
		main.removeString("Validação");
		main.removeString("Software");
		assertTrue("1_4_4", main.onList.contains("Testes"));
		assertTrue("1_4_4", main.onList.contains("Verificação"));
		assertTrue("1_4_4", main.offList.contains("Validação"));
		assertTrue("1_4_4", main.offList.contains("Software"));
		main.addString("Validação");
		assertTrue("1_4_4_1", main.onList.contains("Testes"));
		assertTrue("1_4_4_1", main.onList.contains("Verificação"));
		assertTrue("1_4_4_1", main.onList.contains("Validação"));
		assertTrue("1_4_4_1", main.offList.contains("Software"));
	}

	public void test45() throws Exception {
		System.out.println("Test case 45");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assertTrue("1_4_4_2", main.onList.contains("Testes"));
		assertTrue("1_4_4_2", main.onList.contains("Verificação"));
		assertTrue("1_4_4_2", main.onList.contains("Software"));
		assertTrue("1_4_4_2", main.offList.contains("Validação"));
	}

	public void test46() throws Exception {
		System.out.println("Test case 46");
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Testes");
		assertTrue("1_4_4_3", main.onList.contains("Verificação"));
		assertTrue("1_4_4_3", main.offList.contains("Testes"));
		assertTrue("1_4_4_3", main.offList.contains("Validação"));
		assertTrue("1_4_4_3", main.offList.contains("Software"));
	}

	public void test47() throws Exception {
		System.out.println("Test case 47");
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Verificação");
		assertTrue("1_4_4_4", main.onList.contains("Testes"));
		assertTrue("1_4_4_4", main.offList.contains("Verificação"));
		assertTrue("1_4_4_4", main.offList.contains("Validação"));
		assertTrue("1_4_4_4", main.offList.contains("Software"));
	}

	public void test48() throws Exception {
		System.out.println("Test case 48");
		main.removeString("Software");
		assertTrue("1_5", main.onList.contains("Testes"));
		assertTrue("1_5", main.onList.contains("Verificação"));
		assertTrue("1_5", main.onList.contains("Validação"));
		assertTrue("1_5", main.offList.contains("Software"));
		main.addString("Software");
		assertTrue("1_5_1", main.onList.contains("Testes"));
		assertTrue("1_5_1", main.onList.contains("Verificação"));
		assertTrue("1_5_1", main.onList.contains("Validação"));
		assertTrue("1_5_1", main.onList.contains("Software"));
	}

	public void test49() throws Exception {
		System.out.println("Test case 49");
		main.removeString("Software");
		main.removeString("Testes");
		assertTrue("1_5_2", main.onList.contains("Verificação"));
		assertTrue("1_5_2", main.onList.contains("Validação"));
		assertTrue("1_5_2", main.offList.contains("Testes"));
		assertTrue("1_5_2", main.offList.contains("Software"));
	}

	public void test50() throws Exception {
		System.out.println("Test case 50");
		main.removeString("Software");
		main.removeString("Verificação");
		assertTrue("1_5_3", main.onList.contains("Testes"));
		assertTrue("1_5_3", main.onList.contains("Validação"));
		assertTrue("1_5_3", main.offList.contains("Verificação"));
		assertTrue("1_5_3", main.offList.contains("Software"));
	}

	public void test51() throws Exception {
		System.out.println("Test case 51");
		main.removeString("Software");
		main.removeString("Validação");
		assertTrue("1_5_4", main.onList.contains("Testes"));
		assertTrue("1_5_4", main.onList.contains("Verificação"));
		assertTrue("1_5_4", main.offList.contains("Validação"));
		assertTrue("1_5_4", main.offList.contains("Software"));
	}

}
