//Test code generated by MISTA

package test;

import src.*;

public class MainTester_RT{

	private Main main;
	
	protected void setUp()  throws Exception {
		main = new Main();
		main.onList.add("Testes");
		main.onList.add("Verificação");
		main.onList.add("Validação");
		main.onList.add("Software");
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		setUp();
		main.removeString("Testes");
		assert main.onList.contains("Verificação") : "1_1";
		assert main.onList.contains("Validação") : "1_1";
		assert main.onList.contains("Software") : "1_1";
		assert main.offList.contains("Testes") : "1_1";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_1";
		assert main.onList.contains("Verificação") : "1_1_1";
		assert main.onList.contains("Validação") : "1_1_1";
		assert main.onList.contains("Software") : "1_1_1";
	}

	public void test2() throws Exception {
		System.out.println("Test case 2");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		assert main.onList.contains("Validação") : "1_1_2";
		assert main.onList.contains("Software") : "1_1_2";
		assert main.offList.contains("Testes") : "1_1_2";
		assert main.offList.contains("Verificação") : "1_1_2";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_2_1";
		assert main.onList.contains("Validação") : "1_1_2_1";
		assert main.onList.contains("Software") : "1_1_2_1";
		assert main.offList.contains("Verificação") : "1_1_2_1";
	}

	public void test3() throws Exception {
		System.out.println("Test case 3");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.addString("Verificação");
		assert main.onList.contains("Verificação") : "1_1_2_2";
		assert main.onList.contains("Validação") : "1_1_2_2";
		assert main.onList.contains("Software") : "1_1_2_2";
		assert main.offList.contains("Testes") : "1_1_2_2";
	}

	public void test4() throws Exception {
		System.out.println("Test case 4");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		assert main.onList.contains("Software") : "1_1_2_3";
		assert main.offList.contains("Testes") : "1_1_2_3";
		assert main.offList.contains("Verificação") : "1_1_2_3";
		assert main.offList.contains("Validação") : "1_1_2_3";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_2_3_1";
		assert main.onList.contains("Software") : "1_1_2_3_1";
		assert main.offList.contains("Verificação") : "1_1_2_3_1";
		assert main.offList.contains("Validação") : "1_1_2_3_1";
	}

	public void test5() throws Exception {
		System.out.println("Test case 5");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.addString("Verificação");
		assert main.onList.contains("Verificação") : "1_1_2_3_2";
		assert main.onList.contains("Software") : "1_1_2_3_2";
		assert main.offList.contains("Testes") : "1_1_2_3_2";
		assert main.offList.contains("Validação") : "1_1_2_3_2";
	}

	public void test6() throws Exception {
		System.out.println("Test case 6");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.addString("Validação");
		assert main.onList.contains("Validação") : "1_1_2_3_3";
		assert main.onList.contains("Software") : "1_1_2_3_3";
		assert main.offList.contains("Testes") : "1_1_2_3_3";
		assert main.offList.contains("Verificação") : "1_1_2_3_3";
	}

	public void test7() throws Exception {
		System.out.println("Test case 7");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		assert main.offList.contains("Testes") : "1_1_2_3_4";
		assert main.offList.contains("Verificação") : "1_1_2_3_4";
		assert main.offList.contains("Validação") : "1_1_2_3_4";
		assert main.offList.contains("Software") : "1_1_2_3_4";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_2_3_4_1";
		assert main.offList.contains("Verificação") : "1_1_2_3_4_1";
		assert main.offList.contains("Validação") : "1_1_2_3_4_1";
		assert main.offList.contains("Software") : "1_1_2_3_4_1";
	}

	public void test8() throws Exception {
		System.out.println("Test case 8");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Verificação");
		assert main.onList.contains("Verificação") : "1_1_2_3_4_2";
		assert main.offList.contains("Testes") : "1_1_2_3_4_2";
		assert main.offList.contains("Validação") : "1_1_2_3_4_2";
		assert main.offList.contains("Software") : "1_1_2_3_4_2";
	}

	public void test9() throws Exception {
		System.out.println("Test case 9");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Validação");
		assert main.onList.contains("Validação") : "1_1_2_3_4_3";
		assert main.offList.contains("Testes") : "1_1_2_3_4_3";
		assert main.offList.contains("Verificação") : "1_1_2_3_4_3";
		assert main.offList.contains("Software") : "1_1_2_3_4_3";
	}

	public void test10() throws Exception {
		System.out.println("Test case 10");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Software") : "1_1_2_3_4_4";
		assert main.offList.contains("Testes") : "1_1_2_3_4_4";
		assert main.offList.contains("Verificação") : "1_1_2_3_4_4";
		assert main.offList.contains("Validação") : "1_1_2_3_4_4";
	}

	public void test11() throws Exception {
		System.out.println("Test case 11");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		assert main.onList.contains("Validação") : "1_1_2_4";
		assert main.offList.contains("Testes") : "1_1_2_4";
		assert main.offList.contains("Verificação") : "1_1_2_4";
		assert main.offList.contains("Software") : "1_1_2_4";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_2_4_1";
		assert main.onList.contains("Validação") : "1_1_2_4_1";
		assert main.offList.contains("Verificação") : "1_1_2_4_1";
		assert main.offList.contains("Software") : "1_1_2_4_1";
	}

	public void test12() throws Exception {
		System.out.println("Test case 12");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		main.addString("Verificação");
		assert main.onList.contains("Verificação") : "1_1_2_4_2";
		assert main.onList.contains("Validação") : "1_1_2_4_2";
		assert main.offList.contains("Testes") : "1_1_2_4_2";
		assert main.offList.contains("Software") : "1_1_2_4_2";
	}

	public void test13() throws Exception {
		System.out.println("Test case 13");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Validação") : "1_1_2_4_3";
		assert main.onList.contains("Software") : "1_1_2_4_3";
		assert main.offList.contains("Testes") : "1_1_2_4_3";
		assert main.offList.contains("Verificação") : "1_1_2_4_3";
	}

	public void test14() throws Exception {
		System.out.println("Test case 14");
		setUp();
		main.removeString("Testes");
		main.removeString("Verificação");
		main.removeString("Software");
		main.removeString("Validação");
		assert main.offList.contains("Testes") : "1_1_2_4_4";
		assert main.offList.contains("Verificação") : "1_1_2_4_4";
		assert main.offList.contains("Validação") : "1_1_2_4_4";
		assert main.offList.contains("Software") : "1_1_2_4_4";
	}

	public void test15() throws Exception {
		System.out.println("Test case 15");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		assert main.onList.contains("Verificação") : "1_1_3";
		assert main.onList.contains("Software") : "1_1_3";
		assert main.offList.contains("Testes") : "1_1_3";
		assert main.offList.contains("Validação") : "1_1_3";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_3_1";
		assert main.onList.contains("Verificação") : "1_1_3_1";
		assert main.onList.contains("Software") : "1_1_3_1";
		assert main.offList.contains("Validação") : "1_1_3_1";
	}

	public void test16() throws Exception {
		System.out.println("Test case 16");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		main.addString("Validação");
		assert main.onList.contains("Verificação") : "1_1_3_2";
		assert main.onList.contains("Validação") : "1_1_3_2";
		assert main.onList.contains("Software") : "1_1_3_2";
		assert main.offList.contains("Testes") : "1_1_3_2";
	}

	public void test17() throws Exception {
		System.out.println("Test case 17");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Verificação");
		assert main.onList.contains("Software") : "1_1_3_3";
		assert main.offList.contains("Testes") : "1_1_3_3";
		assert main.offList.contains("Verificação") : "1_1_3_3";
		assert main.offList.contains("Validação") : "1_1_3_3";
	}

	public void test18() throws Exception {
		System.out.println("Test case 18");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		assert main.onList.contains("Verificação") : "1_1_3_4";
		assert main.offList.contains("Testes") : "1_1_3_4";
		assert main.offList.contains("Validação") : "1_1_3_4";
		assert main.offList.contains("Software") : "1_1_3_4";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_3_4_1";
		assert main.onList.contains("Verificação") : "1_1_3_4_1";
		assert main.offList.contains("Validação") : "1_1_3_4_1";
		assert main.offList.contains("Software") : "1_1_3_4_1";
	}

	public void test19() throws Exception {
		System.out.println("Test case 19");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Validação");
		assert main.onList.contains("Verificação") : "1_1_3_4_2";
		assert main.onList.contains("Validação") : "1_1_3_4_2";
		assert main.offList.contains("Testes") : "1_1_3_4_2";
		assert main.offList.contains("Software") : "1_1_3_4_2";
	}

	public void test20() throws Exception {
		System.out.println("Test case 20");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Verificação") : "1_1_3_4_3";
		assert main.onList.contains("Software") : "1_1_3_4_3";
		assert main.offList.contains("Testes") : "1_1_3_4_3";
		assert main.offList.contains("Validação") : "1_1_3_4_3";
	}

	public void test21() throws Exception {
		System.out.println("Test case 21");
		setUp();
		main.removeString("Testes");
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Verificação");
		assert main.offList.contains("Testes") : "1_1_3_4_4";
		assert main.offList.contains("Verificação") : "1_1_3_4_4";
		assert main.offList.contains("Validação") : "1_1_3_4_4";
		assert main.offList.contains("Software") : "1_1_3_4_4";
	}

	public void test22() throws Exception {
		System.out.println("Test case 22");
		setUp();
		main.removeString("Testes");
		main.removeString("Software");
		assert main.onList.contains("Verificação") : "1_1_4";
		assert main.onList.contains("Validação") : "1_1_4";
		assert main.offList.contains("Testes") : "1_1_4";
		assert main.offList.contains("Software") : "1_1_4";
		main.addString("Testes");
		assert main.onList.contains("Testes") : "1_1_4_1";
		assert main.onList.contains("Verificação") : "1_1_4_1";
		assert main.onList.contains("Validação") : "1_1_4_1";
		assert main.offList.contains("Software") : "1_1_4_1";
	}

	public void test23() throws Exception {
		System.out.println("Test case 23");
		setUp();
		main.removeString("Testes");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Verificação") : "1_1_4_2";
		assert main.onList.contains("Validação") : "1_1_4_2";
		assert main.onList.contains("Software") : "1_1_4_2";
		assert main.offList.contains("Testes") : "1_1_4_2";
	}

	public void test24() throws Exception {
		System.out.println("Test case 24");
		setUp();
		main.removeString("Testes");
		main.removeString("Software");
		main.removeString("Verificação");
		assert main.onList.contains("Validação") : "1_1_4_3";
		assert main.offList.contains("Testes") : "1_1_4_3";
		assert main.offList.contains("Verificação") : "1_1_4_3";
		assert main.offList.contains("Software") : "1_1_4_3";
	}

	public void test25() throws Exception {
		System.out.println("Test case 25");
		setUp();
		main.removeString("Testes");
		main.removeString("Software");
		main.removeString("Validação");
		assert main.onList.contains("Verificação") : "1_1_4_4";
		assert main.offList.contains("Testes") : "1_1_4_4";
		assert main.offList.contains("Validação") : "1_1_4_4";
		assert main.offList.contains("Software") : "1_1_4_4";
	}

	public void test26() throws Exception {
		System.out.println("Test case 26");
		setUp();
		main.removeString("Verificação");
		assert main.onList.contains("Testes") : "1_2";
		assert main.onList.contains("Validação") : "1_2";
		assert main.onList.contains("Software") : "1_2";
		assert main.offList.contains("Verificação") : "1_2";
		main.addString("Verificação");
		assert main.onList.contains("Testes") : "1_2_1";
		assert main.onList.contains("Verificação") : "1_2_1";
		assert main.onList.contains("Validação") : "1_2_1";
		assert main.onList.contains("Software") : "1_2_1";
	}

	public void test27() throws Exception {
		System.out.println("Test case 27");
		setUp();
		main.removeString("Verificação");
		main.removeString("Testes");
		assert main.onList.contains("Validação") : "1_2_2";
		assert main.onList.contains("Software") : "1_2_2";
		assert main.offList.contains("Testes") : "1_2_2";
		assert main.offList.contains("Verificação") : "1_2_2";
	}

	public void test28() throws Exception {
		System.out.println("Test case 28");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		assert main.onList.contains("Testes") : "1_2_3";
		assert main.onList.contains("Software") : "1_2_3";
		assert main.offList.contains("Verificação") : "1_2_3";
		assert main.offList.contains("Validação") : "1_2_3";
		main.addString("Verificação");
		assert main.onList.contains("Testes") : "1_2_3_1";
		assert main.onList.contains("Verificação") : "1_2_3_1";
		assert main.onList.contains("Software") : "1_2_3_1";
		assert main.offList.contains("Validação") : "1_2_3_1";
	}

	public void test29() throws Exception {
		System.out.println("Test case 29");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		main.addString("Validação");
		assert main.onList.contains("Testes") : "1_2_3_2";
		assert main.onList.contains("Validação") : "1_2_3_2";
		assert main.onList.contains("Software") : "1_2_3_2";
		assert main.offList.contains("Verificação") : "1_2_3_2";
	}

	public void test30() throws Exception {
		System.out.println("Test case 30");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Testes");
		assert main.onList.contains("Software") : "1_2_3_3";
		assert main.offList.contains("Testes") : "1_2_3_3";
		assert main.offList.contains("Verificação") : "1_2_3_3";
		assert main.offList.contains("Validação") : "1_2_3_3";
	}

	public void test31() throws Exception {
		System.out.println("Test case 31");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		assert main.onList.contains("Testes") : "1_2_3_4";
		assert main.offList.contains("Verificação") : "1_2_3_4";
		assert main.offList.contains("Validação") : "1_2_3_4";
		assert main.offList.contains("Software") : "1_2_3_4";
		main.addString("Verificação");
		assert main.onList.contains("Testes") : "1_2_3_4_1";
		assert main.onList.contains("Verificação") : "1_2_3_4_1";
		assert main.offList.contains("Validação") : "1_2_3_4_1";
		assert main.offList.contains("Software") : "1_2_3_4_1";
	}

	public void test32() throws Exception {
		System.out.println("Test case 32");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Validação");
		assert main.onList.contains("Testes") : "1_2_3_4_2";
		assert main.onList.contains("Validação") : "1_2_3_4_2";
		assert main.offList.contains("Verificação") : "1_2_3_4_2";
		assert main.offList.contains("Software") : "1_2_3_4_2";
	}

	public void test33() throws Exception {
		System.out.println("Test case 33");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Testes") : "1_2_3_4_3";
		assert main.onList.contains("Software") : "1_2_3_4_3";
		assert main.offList.contains("Verificação") : "1_2_3_4_3";
		assert main.offList.contains("Validação") : "1_2_3_4_3";
	}

	public void test34() throws Exception {
		System.out.println("Test case 34");
		setUp();
		main.removeString("Verificação");
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Testes");
		assert main.offList.contains("Testes") : "1_2_3_4_4";
		assert main.offList.contains("Verificação") : "1_2_3_4_4";
		assert main.offList.contains("Validação") : "1_2_3_4_4";
		assert main.offList.contains("Software") : "1_2_3_4_4";
	}

	public void test35() throws Exception {
		System.out.println("Test case 35");
		setUp();
		main.removeString("Verificação");
		main.removeString("Software");
		assert main.onList.contains("Testes") : "1_2_4";
		assert main.onList.contains("Validação") : "1_2_4";
		assert main.offList.contains("Verificação") : "1_2_4";
		assert main.offList.contains("Software") : "1_2_4";
		main.addString("Verificação");
		assert main.onList.contains("Testes") : "1_2_4_1";
		assert main.onList.contains("Verificação") : "1_2_4_1";
		assert main.onList.contains("Validação") : "1_2_4_1";
		assert main.offList.contains("Software") : "1_2_4_1";
	}

	public void test36() throws Exception {
		System.out.println("Test case 36");
		setUp();
		main.removeString("Verificação");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Testes") : "1_2_4_2";
		assert main.onList.contains("Validação") : "1_2_4_2";
		assert main.onList.contains("Software") : "1_2_4_2";
		assert main.offList.contains("Verificação") : "1_2_4_2";
	}

	public void test37() throws Exception {
		System.out.println("Test case 37");
		setUp();
		main.removeString("Verificação");
		main.removeString("Software");
		main.removeString("Testes");
		assert main.onList.contains("Validação") : "1_2_4_3";
		assert main.offList.contains("Testes") : "1_2_4_3";
		assert main.offList.contains("Verificação") : "1_2_4_3";
		assert main.offList.contains("Software") : "1_2_4_3";
	}

	public void test38() throws Exception {
		System.out.println("Test case 38");
		setUp();
		main.removeString("Verificação");
		main.removeString("Software");
		main.removeString("Validação");
		assert main.onList.contains("Testes") : "1_2_4_4";
		assert main.offList.contains("Verificação") : "1_2_4_4";
		assert main.offList.contains("Validação") : "1_2_4_4";
		assert main.offList.contains("Software") : "1_2_4_4";
	}

	public void test39() throws Exception {
		System.out.println("Test case 39");
		setUp();
		main.removeString("Validação");
		assert main.onList.contains("Testes") : "1_3";
		assert main.onList.contains("Verificação") : "1_3";
		assert main.onList.contains("Software") : "1_3";
		assert main.offList.contains("Validação") : "1_3";
		main.addString("Validação");
		assert main.onList.contains("Testes") : "1_3_1";
		assert main.onList.contains("Verificação") : "1_3_1";
		assert main.onList.contains("Validação") : "1_3_1";
		assert main.onList.contains("Software") : "1_3_1";
	}

	public void test40() throws Exception {
		System.out.println("Test case 40");
		setUp();
		main.removeString("Validação");
		main.removeString("Testes");
		assert main.onList.contains("Verificação") : "1_3_2";
		assert main.onList.contains("Software") : "1_3_2";
		assert main.offList.contains("Testes") : "1_3_2";
		assert main.offList.contains("Validação") : "1_3_2";
	}

	public void test41() throws Exception {
		System.out.println("Test case 41");
		setUp();
		main.removeString("Validação");
		main.removeString("Verificação");
		assert main.onList.contains("Testes") : "1_3_3";
		assert main.onList.contains("Software") : "1_3_3";
		assert main.offList.contains("Verificação") : "1_3_3";
		assert main.offList.contains("Validação") : "1_3_3";
	}

	public void test42() throws Exception {
		System.out.println("Test case 42");
		setUp();
		main.removeString("Validação");
		main.removeString("Software");
		assert main.onList.contains("Testes") : "1_3_4";
		assert main.onList.contains("Verificação") : "1_3_4";
		assert main.offList.contains("Validação") : "1_3_4";
		assert main.offList.contains("Software") : "1_3_4";
		main.addString("Validação");
		assert main.onList.contains("Testes") : "1_3_4_1";
		assert main.onList.contains("Verificação") : "1_3_4_1";
		assert main.onList.contains("Validação") : "1_3_4_1";
		assert main.offList.contains("Software") : "1_3_4_1";
	}

	public void test43() throws Exception {
		System.out.println("Test case 43");
		setUp();
		main.removeString("Validação");
		main.removeString("Software");
		main.addString("Software");
		assert main.onList.contains("Testes") : "1_3_4_2";
		assert main.onList.contains("Verificação") : "1_3_4_2";
		assert main.onList.contains("Software") : "1_3_4_2";
		assert main.offList.contains("Validação") : "1_3_4_2";
	}

	public void test44() throws Exception {
		System.out.println("Test case 44");
		setUp();
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Testes");
		assert main.onList.contains("Verificação") : "1_3_4_3";
		assert main.offList.contains("Testes") : "1_3_4_3";
		assert main.offList.contains("Validação") : "1_3_4_3";
		assert main.offList.contains("Software") : "1_3_4_3";
	}

	public void test45() throws Exception {
		System.out.println("Test case 45");
		setUp();
		main.removeString("Validação");
		main.removeString("Software");
		main.removeString("Verificação");
		assert main.onList.contains("Testes") : "1_3_4_4";
		assert main.offList.contains("Verificação") : "1_3_4_4";
		assert main.offList.contains("Validação") : "1_3_4_4";
		assert main.offList.contains("Software") : "1_3_4_4";
	}

	public void test46() throws Exception {
		System.out.println("Test case 46");
		setUp();
		main.removeString("Software");
		assert main.onList.contains("Testes") : "1_4";
		assert main.onList.contains("Verificação") : "1_4";
		assert main.onList.contains("Validação") : "1_4";
		assert main.offList.contains("Software") : "1_4";
		main.addString("Software");
		assert main.onList.contains("Testes") : "1_4_1";
		assert main.onList.contains("Verificação") : "1_4_1";
		assert main.onList.contains("Validação") : "1_4_1";
		assert main.onList.contains("Software") : "1_4_1";
	}

	public void test47() throws Exception {
		System.out.println("Test case 47");
		setUp();
		main.removeString("Software");
		main.removeString("Testes");
		assert main.onList.contains("Verificação") : "1_4_2";
		assert main.onList.contains("Validação") : "1_4_2";
		assert main.offList.contains("Testes") : "1_4_2";
		assert main.offList.contains("Software") : "1_4_2";
	}

	public void test48() throws Exception {
		System.out.println("Test case 48");
		setUp();
		main.removeString("Software");
		main.removeString("Verificação");
		assert main.onList.contains("Testes") : "1_4_3";
		assert main.onList.contains("Validação") : "1_4_3";
		assert main.offList.contains("Verificação") : "1_4_3";
		assert main.offList.contains("Software") : "1_4_3";
	}

	public void test49() throws Exception {
		System.out.println("Test case 49");
		setUp();
		main.removeString("Software");
		main.removeString("Validação");
		assert main.onList.contains("Testes") : "1_4_4";
		assert main.onList.contains("Verificação") : "1_4_4";
		assert main.offList.contains("Validação") : "1_4_4";
		assert main.offList.contains("Software") : "1_4_4";
	}

	public void testAll() throws Exception {
		test1();
		test2();
		test3();
		test4();
		test5();
		test6();
		test7();
		test8();
		test9();
		test10();
		test11();
		test12();
		test13();
		test14();
		test15();
		test16();
		test17();
		test18();
		test19();
		test20();
		test21();
		test22();
		test23();
		test24();
		test25();
		test26();
		test27();
		test28();
		test29();
		test30();
		test31();
		test32();
		test33();
		test34();
		test35();
		test36();
		test37();
		test38();
		test39();
		test40();
		test41();
		test42();
		test43();
		test44();
		test45();
		test46();
		test47();
		test48();
		test49();
	}

	public static void main(String[] args) throws Exception {
		 new MainTester_RT().testAll();
	}

}
