//Test code generated by MISTA

package test;

import src.Account;
import junit.framework.*;

public class AccountTester_RT extends TestCase{

	private Account account;
	
	protected void setUp()  throws Exception {
		account = new Account();
	}
	
	public void test1() throws Exception {
		System.out.println("Test case 1");
		account.close();
		assertTrue("1_1", account.isClosed());
		account.open();
		assertTrue("1_1_1", !account.isClosed() && !account.isIndebted());
		!account.isClosed() && account.isIndebted();
	}

}
